const mockdata = [
  {
    id: "1",
    title: "Brunlees Court",
    address: "19-23 Cambridge Road, Southport",
    type: "IndependentLiving",
    price: 483000,
    img: "./img/home1.jpg",
  },
  {
    id: "2",
    title: "Charlotte Court",
    address: "514 Muller Mount",
    type: "IndependentLiving",
    price: 260000,
    img: "./img/home2.jpg",
  },
  {
    id: "3",
    title: "Protocol Virginia",
    address: "19-10 Adam Street, London",
    type: "IndependentLiving",
    price: 468000,
    img: "./img/home3.jpg",
  },
  {
    id: "4",
    title: "infomediaries Row",
    address: "451 Swaniawski Ford",
    type: "SupportAvailable",
    price: 234000,
    img: "./img/home4.jpg",
  },
  {
    id: "5",
    title: "SMS",
    address: "67160 Huel Well",
    type: "SupportAvailable",
    price: 931000,
    img: "./img/home5.jpg",
  },
  {
    id: "6",
    title: "Checking Account technologies",
    address: "1352 Pete Shoals",
    type: "IndependentLiving",
    price: 449000,
    img: "./img/home6.jpg",
  },
  {
    id: "7",
    title: "New Caledonia invoice",
    address: "88517 Bernier Vista",
    type: "SupportAvailable",
    price: 326000,
    img: "./img/home7.jpg",
  },
  {
    id: "8",
    title: "Architect",
    address: "09540 Madge River",
    type: "IndependentLiving",
    price: 369000,
    img: "./img/home8.jpg",
  },
  {
    id: "9",
    title: "Indexing application",
    address: "1603 Kutch Well",
    type: "IndependentLiving",
    price: 363000,
    img: "./img/home9.jpg",
  },
  {
    id: "10",
    title: "Summit",
    address: "7645 Iliana Course",
    type: "IndependentLiving",
    price: 788000,
    img: "./img/home10.jpg",
  },
  {
    id: "11",
    title: "Web cross-platform",
    address: "46820 Barton Avenue",
    type: "IndependentLiving",
    price: 850000,
    img: "./img/home11.jpg",
  },
  {
    id: "12",
    title: "Virtual Fantastic Granite",
    address: "471 Marshall Street",
    type: "IndependentLiving",
    price: 214000,
    img: "./img/home12.jpg",
  },
];
